language: go
sudo: false
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - go test -v demizer/go-rst/...
  - go test -covermode=count -coverprofile=profile.cov
  - goveralls -coverprofile=profile.cov -service=travis-ci
